// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8R0pVTa16k4PvHJQsVMun9AibzhXyWk',
    appId: '1:917529544134:web:b1e85c0c3f0fafae6b5ec7',
    messagingSenderId: '917529544134',
    projectId: 'seo-flutterexample-112354',
    authDomain: 'seo-flutterexample-112354.firebaseapp.com',
    storageBucket: 'seo-flutterexample-112354.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgz0Q0Lp3Ynv0G6ggUjKUPEbagbCaKsA',
    appId: '1:917529544134:android:e4d793074de8f5c46b5ec7',
    messagingSenderId: '917529544134',
    projectId: 'seo-flutterexample-112354',
    storageBucket: 'seo-flutterexample-112354.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-UrEYkCUpPP7dvwoiKYaEpkQykc4ZADs',
    appId: '1:917529544134:ios:f92328c80fddf4926b5ec7',
    messagingSenderId: '917529544134',
    projectId: 'seo-flutterexample-112354',
    storageBucket: 'seo-flutterexample-112354.appspot.com',
    iosClientId: '917529544134-jg4g2b1rsnipb082ubl5uskbctgb8vqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.signview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-UrEYkCUpPP7dvwoiKYaEpkQykc4ZADs',
    appId: '1:917529544134:ios:1f3cb8c80295c28c6b5ec7',
    messagingSenderId: '917529544134',
    projectId: 'seo-flutterexample-112354',
    storageBucket: 'seo-flutterexample-112354.appspot.com',
    iosClientId: '917529544134-nuu3o2qrqqmss4aiojlujpoc2rb6qfhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.signview.RunnerTests',
  );
}
